data:
    dataset: miniImageNet
    image_size: 84
    image_channel: 3

model:
    name: protonet
    ckpt_dir: /home/keeeehun/source/meta/task1_1shot/model_best.pth

training:
    epochs: 100
    val_freq: 20

    classes_per_it_tr: 30   # way
    num_support_tr: 1   # shot
    num_query_tr: 15    # query
    episodes_tr: 100

    classes_per_it_val: 5
    num_support_val: 1
    num_query_val: 15
    episodes_val: 100

optim:
    lr: 0.001
    lr_scheduler_gamma: 0.5
    lr_scheduler_step: 20